# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauranthub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='cuisine_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restauranttype',
            name='restaurant_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
